### ISSUE TITLE
Error Uploading Note with image

### ISSUE THREAD

**Issue by afusalan** [alangrainger/share-note#113] opened 2024-06-21 22:24 UTC
I attach an image to my note as ![[image.jpg]] like this but it gives me an error. I tried it with different images and with different notes and renamed the name of the image but no luck. I tried deleting the image from the note and it uploaded No problem.

![SmartSelect_20240622_012259_Obsidian](https://github.com/alangrainger/share-note/assets/73854460/7e6bb928-b403-446d-800a-fbfe20e0a8b8)

**Comment by ann40** [comment] 2024-07-04 16:51
same to me

**Comment by alangrainger** [comment] 2024-08-01 18:33
I think this must have been a server or network issue at the time, as images have always been part of Share Note's functionality.

I will close this request as I cannot reproduce or find any issue - but please let me know if you're still experiencing this.

**Closed by alangrainger** 2024-08-01 18:33 UTC
Labels: bug

**Comment by hyuei** [comment] 2024-08-05 21:57
Sorry, this is still a problem with me, even with the latest update. image will resulting in failed upload. is there anything I could do to help debug this? this happened since the last 3-4 updates i think. before, I could upload images flawslessly.
from what i see, the process stopped immediately after "processing attachments".

**Comment by alangrainger** [comment] 2024-08-12 19:49
Thanks @hyuei - I've tracked down the issue with image uploading on mobile and that should be fixed in 0.8.15.
