### ISSUE TITLE
Deleting old notes after re-sharing

### ISSUE THREAD

**Issue by paradeiser** [alangrainger/share-note#57] opened 2023-12-05 14:19 UTC
When re-sharing (either using the drop-down menu on the top right, or the icon in the properties pane), I often get a new URL / ID assigned. But the old link stays active.

This way, the old note remains online without any changes, but there is also no way to delete or revoke this (old) shared note. So there is no way to take it down anymore.

I assume, when re-sharing the link / ID should actually stay the same, so updates will be available after re-sharing for people I already shared the link with.

**Comment by alangrainger** [comment] 2023-12-05 14:31
The link should stay the same when re-sharing a note. I suggest testing in the sandbox vault, in case there is some other plugin affecting this.

**Comment by cjl12377** [comment] 2024-03-25 02:40
@paradeiser did you find out which plugin was causing this issue?

**Comment by paradeiser** [comment] 2024-08-29 17:51
after a lot of trial and error I suspect the Lint setting:
```
Format Tags in YAML
Remove Hashtags from tags in the YAML frontmatter, as they make the tags there invalid.
```
as it also removes the hashtag from the share_link value - although it's not within the "tags" section.

I also reported this on https://github.com/platers/obsidian-linter/issues/1155

**Comment by alangrainger** [comment] 2024-08-29 17:55
@paradeiser that will be exactly what the issue is, because it's changing the share link URL from `r0w1vdtw` to `r0w1vdtwgoaVfYU2NExAphdG8oHzVUZ2h8E22JDbJHC5BBEsZPo`, which are two very different remote URLs.

Thank you for further investigating that. I'll close this issue as unfortunately there's nothing I can do from my plugin to stop Linter from altering that non-tag frontmatter property.

@cjl12377 - please see above for the solution.

**Closed by alangrainger** 2024-08-29 17:55 UTC
Labels: bug

**Comment by pjkaufman** [comment] 2024-08-31 21:32
Sorry about the issue here. I believe I have a fix for this in the Linter and it should fix this going forward.
